name: PHP Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.4", "8.2", "8.3"]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer


      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run php compatibility test
        run: composer test:compat

      - name: Run phpstan test
        run: composer test:stan

      - name: Run phpunit test
        run: composer test:unit

      - name: Generate zip file
        if: matrix.php-versions == '8.3'
        run: composer release:zip ${{ github.sha }}

      - name: Upload zip file
        if: matrix.php-versions == '8.3'
        uses: actions/upload-artifact@v4
        with:
          name: om4-custom-css.zip
          path: om4-custom-css.zip
